### ISSUE TITLE
Not working with tabbed and vertical/horizontal mixed containers

### ISSUE THREAD

**Issue by indeedwatson** [miseran/i3-tools#1]
I have `workspace_layout tabbed` by default, and I switch to vertical splits if I need it by taking one tab and moving it to the right of another window.

Right now for example I have firefox occupying most of my screen and a narrow terminal on the right.

However, if I do `focus-tool left` from that terminal I get the following error:

```python
Traceback (most recent call last):
  File "./focus-tool", line 171, in <module>
    main(sys.argv[1])
  File "./focus-tool", line 159, in main
    focus_direction(direction)
  File "./focus-tool", line 100, in focus_direction
    node = focused_child(node)
  File "./focus-tool", line 20, in focused_child
    return next(focused_order(node))
  File "./focus-tool", line 14, in focused_order
    for focus_id in node.focus:
AttributeError: 'Con' object has no attribute 'focus'
```

**Comment by miseran** [comment]
I haven't been able to reproduce this. What version of i3ipc-python do you have installed?

**Comment by indeedwatson** [comment]
Apparently my install of i3ipc-python was fucked up, I reinstalled and it seems to be working.
